import InterpolationManager from '../../segmentation/InterpolationManager/InterpolationManager';
export default function acceptAutogeneratedInterpolations(annotationGroupSelector, selector) {
    InterpolationManager.acceptAutoGenerated(annotationGroupSelector, selector);
}
