import type { AcceptInterpolationSelector } from '../../../types/InterpolationTypes';
import type AnnotationGroupSelector from '../../../types/AnnotationGroupSelector';
export default function acceptAutogeneratedInterpolations(annotationGroupSelector: AnnotationGroupSelector, selector: AcceptInterpolationSelector): void;
