export type BaseContourStyle = {
    outlineWidth?: number;
    outlineOpacity?: number;
    outlineDash?: string;
    activeSegmentOutlineWidthDelta?: number;
    renderOutline?: boolean;
    renderFill?: boolean;
    fillAlpha?: number;
};
export type InactiveContourStyle = {
    outlineWidthInactive?: number;
    outlineOpacityInactive?: number;
    outlineDashInactive?: string;
    fillAlphaInactive?: number;
    renderOutlineInactive?: boolean;
    renderFillInactive?: boolean;
};
export type AutoGeneratedContourStyle = {
    outlineWidthAutoGenerated?: number;
    outlineDashAutoGenerated?: string;
    fillAlphaAutoGenerated?: number;
};
export type ContourStyle = BaseContourStyle & InactiveContourStyle & AutoGeneratedContourStyle;
export type ContourSegmentationData = {
    geometryIds?: string[];
    annotationUIDsMap?: Map<number, Set<string>>;
};
